favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.4892473
  brandStrength: 0.9069952662102878
  lightness: 0.453405
  brandColors:
    - '#1F0F0B'
    - '#662615'
    - '#895442'
    - '#FEFFFF'
    - '#E0A387'
  rhythmicContrast: 0
typography_spectrum: 0.9103943
layout_spectrum: 0.1716537051834166
analytics:
  twitter: null
  google: null
  facebook: null
name: morganrusler
