name: morganrusler
favicon: null
layout_spectrum: 0.1716537051834166
typography_spectrum: 0.5700700394809246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9069952662102878
  lightness: 0.44873539078980684
  saturation: 0.9047484553884715
  rhythmicContrast: 0.4278003014624119
purpose: []
